trigger: none

pool:
 vmImage: 'ubunut-16.04'

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - script: echo "A"
  - job: A2
    steps:
    - script: echo "A2"
stages:
- stage: B
  jobs:
  - job: B1
    steps:
    - script: echo "B"
  - job: B2
    steps:
    - script: echo "B2"
  